build:all


all:preBuild a b c d e f g h i j k l

preBuild:
	./duplicateFiles.sh

a:
	./shell01.sh

b:
	./shell02.sh

c:
	./shell03.sh

d:
	./shell04.sh

e:
	./shell05.sh

f:
	./shell06.sh

g:
	./shell07.sh

h:
	./shell08.sh

i:
	./shell09.sh

j:
	./shell010.sh

k:
	./shell011.sh

l:
	./shell012.sh

.PHONY:clean
clean:
	rm -rf shell*

